name: restaurant-reviews-sentiment-analysis
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade pip
          pip install pygit2
          pip install -r requirements-pip.txt
          dvc repro 
          git fetch --prune
          dvc metrics diff --show-md main > report.md
          # Add figure to the report
          echo "## Performance" >> report.md
          cml-publish output/confusion_matrix_heat_map.png --md >> report.md
          cml-send-comment report.md
