name: restaurant-reviews-sentiment-analysis
on: [push]
jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.8.16

    steps:
      - uses: actions/checkout@v3
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v11
        with:
          default: "${{ matrix.python }}"
          command: pip install -U pip # upgrade pip after installing python

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements-pip.txt
          dvc repro 

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Add figure to the report
          echo "## Validating results by region"
          cml-publish output/confusion_matrix_heat_map.png --md >> report.md
          cml-send-comment report.md
