name: Versioning
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade pip setuptools wheel
          pip install -r requirements-pip.txt

      #   - name: Download Data
      #     run: |
      #       dvc pull -r myremote

      - name: Build Models
        run: |
          python3 scripts/create_models.py

      - name: Release Models
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Release Classifier Sentiment Model
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: models/c2_Classifier_Sentiment_Model
          asset_name: c2_Classifier_Sentiment_Model
          asset_content_type: application/octet-stream

      - name: Release Bag of Words Sentiment Model
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: models/c1_BoW_Sentiment_Model.pkl
          asset_name: c1_BoW_Sentiment_Model.pkl
          asset_content_type: application/octet-stream
